name: Data Import and Processing

on:
  push:
    paths:
      - 'scripts/**'
  workflow_dispatch:

jobs:
  import-and-process-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '24.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Import Data to Cosmos MongoDB
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      run: |
        python scripts/import_raw_data.py
      timeout-minutes: 10  # Set a timeout of 15 minutes for this step
