name: Data Import and Processing

on:
  push:
    paths:
      - 'scripts/**'
  workflow_dispatch:

jobs:
  import-and-process-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    - name: Upgrade pip to version 24.1
      run: python -m pip install --upgrade pip==24.1

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Import Data to Cosmos MongoDB
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      run: python scripts/import_raw_data.py
      timeout-minutes: 10  # Set a timeout of 10 minutes for this step
