name: Data Import and Processing

on:
  push:
    branches:
      - feature/import-csv-to-mongodb
    paths:
      - 'scripts/**'
  workflow_dispatch:

jobs:
  import-and-process-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Check if scripts directory exists
      run: |
          if [ ! -d "scripts" ]; then
            echo "scripts directory does not exist."
            exit 1
          fi

    - name: Check if script files exist
      run: |
          if [ ! -f "scripts/import_raw_data.py" ]; then
            echo "import_raw_data.py does not exist in scripts directory."
            exit 1
          fi

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Validate environment variables
      run: |
          if [ -z "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" ]; then
            echo "AZURE_STORAGE_CONNECTION_STRING is not set."
            exit 1
          else
            echo "AZURE_STORAGE_CONNECTION_STRING is set"
          fi

          if [ -z "${{ secrets.MONGO_CONNECTION_STRING }}" ]; then
            echo "MONGO_CONNECTION_STRING is not set. Check secret at repository settings."
            exit 1
          else
            echo "MONGO_CONNECTION_STRING is set"
          fi

    - name: Import Data to Cosmos MongoDB
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      run: |
        python scripts/import_raw_data.py
      timeout-minutes: 1440 #Set a timeout of 24 hours